config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/users', to: 'users#show', as: 'curr_user'
  get '/newPet', to: 'pets#new', as: 'new_pet'
  post '/createPet', to: 'pets#create', as: 'create_pet'
  get '/createFailed', to: 'request#create_failed', as: 'create_failed'
  get '/searchPets', to: 'pets#show', as: 'search_pets'
  patch '/request', to: 'request#new', as: 'new_request'
  post '/request', to: 'request#delete', as: 'delete_request'
  post '/createRequest', to: 'request#create', as: 'create_request'
  post '/deletePet', to: 'pets#delete', as: 'delete_pet'
  post '/acceptRequest', to: 'request#accept', as: 'accept_request'
  post '/declineRequest', to: 'request#decline', as: 'decline_request'
  post '/searchPets', to: 'pets#show', as: 'patch_search_pets'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :User
	has_many :requests
	has_one :review
	validates :name, :presence =>{:message=>"Please enter the name of your pet."}
	validates :animal_type, :presence =>{:message=>"Please select an animal type, or choose 'other' if your animal type is not listed "}
	validates :start_date, :presence =>{:message=>"The start date can't be blank"}
	validates :start_time, :presence =>{:message=>"The start time can't be blank"}
	#validates :start_time, presence: true
	#NS add back in start_time validation when calendar is set up!
	validates :duration, :presence =>{:message=>"The duration field can't be blank"}
	validates :address, :presence =>{:message=>"The address field can't be blank"}

	default_scope { order('name ASC') }
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :pet
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :pet

	validates :rating, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pets
  has_many :requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		#if current_user
			#@curr_user = User.find(current_user.id)
			
		#else
		#	redirect_to new_user_session_path, notice: 'You are not logged in.'
		#end
		if current_user
			@curr_user_id = current_user.id
		else
			@curr_user_id = nil
		end

	end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def new
    @pet = Pet.new
    @user_id = params[:curr_user]

  end

  def show
    if current_user
      @user_id = current_user.id
    else
      @user_id = 0
    end
    @pet = Pet.new
    @pets = Pet.all
    if params[:pet] != nil && params[:pet][:animal_type] != ""
      @pets = @pets.where(:animal_type=>params[:pet][:animal_type])
    end
    if params[:pet] != nil && params[:pet]["start_date(1i)"] != nil
      start_date = params[:pet][:start_date]
      @pets = @pets.where(start_date: start_date)
    end
    if params[:pet] != nil && params[:pet][:duration] != ""
      @pets = @pets.where(:duration=>params[:pet][:duration])
    end
  end

  def create
    @pet = Pet.create(:name => params[:pet][:name],  
      :characteristic=>params[:pet][:characteristic], 
      :animal_type=> params[:pet][:animal_type], 
      :image_url => params[:pet][:image_url],
      :address => params[:pet][:address],
      :start_time=> params[:pet][:start_time],
      :start_date=> params[:pet][:start_date],
      :duration => params[:pet][:duration], :user_id =>params[:curr_user])

    if @pet.save

    #@pet.update_all(:user_id => current_user.id)
    #@pet.update(:user_id => params[:curr_user])
      redirect_to curr_user_path(:curr_user=>params[:curr_user])
    else
      flash[:error] = @pet.errors.first[1]
      #@message.errors[:name].join(", ")
      #flash.now[:error]
      #flash.now[:error] = @message.errors[:name].first 
      redirect_to new_pet_path(:curr_user=>current_user.id)
    end
  end

  def delete
    #delete pet with the params id
    @pets = Pet.where(:id=>params[:pet_id]).first
    @pets.delete
    
    #delete all requests associated with that pet
    @pets.requests.each do |request|
      request.delete
    end

    redirect_to curr_user_path(curr_user: params[:user_id])
  end
end

app/controllers/request_controller.rb
class RequestController < ApplicationController
  def new
    if current_user
      #@curr_user = User.find(current_user.id)
      #@user = User.find(current_user.id)

      @request = Request.new
      @pet = Pet.where(id: params[:pet_id]).first
      #@pet = Pet.find(params[:pet_id])
      @user_id = current_user.id

      if @pet.user_id == @user_id
        redirect_to search_pets_path, notice: "You can't request your own pet! Silly Willy."

      elsif !Request.where(:user_id=>@user_id, :pet_id=>@pet.id).blank?
        #request for this pet already exists
        respond_to do |format|
          format.html{ redirect_to search_pets_path, notice: "You have already requested this pet! Silly Willy."}
        end
        #render html: "<script>alert('You have already created a request for this pet!')</script>".html_safe
      end


    else
      redirect_to new_user_session_path, notice: 'Before making a request, You must log in!'
    end

  end

  def create
    @pet = Pet.where(id: params[:pet_id]).first
    @user_id = params[:curr_user]

    @request = Request.create(:pet_id => params[:pet_id], :user_id => params[:curr_user], :status=>-1, :request_message=> params[:request][:request_message] )

    if !@request.save
      redirect_to create_failed_path
    end

  end

  def create_failed
  end

  def accept
    @request = Request.where(id: params[:request_id]).first
    @request.update(status: 1)
    redirect_to curr_user_path
  end

  def decline
    @request = Request.where(id: params[:request_id]).first
    @request.update(status: 0)
    redirect_to curr_user_path
  end


  def delete
    p = Request.where(:pet_id=>params[:pet_id]).first
    p.delete 
    redirect_to root_path

  end

end

app/controllers/requests_controller.rb
class RequestController < ApplicationController
  def new
    @request = Request.new
    @pet = Pet.where(id: params[:pet_id]).first
    #@pet = Pet.find(params[:pet_id])
    @user_id = params[:user_id]
    #if !(Request.where(:user_id=>@user_id, :pet_id=>@pet.id).blank?)
    #  #request for this pet already exists
    #  render html: "<script>alert('You have already created a request for this pet!')</script>".html_safe
    #end

  end

  def create
    @pet = Pet.where(id: params[:pet_id]).first
    @user_id = params[:curr_user]
    @request = Request.create(:pet_id => params[:pet_id], :user_id => params[:curr_user], :status=>false, :request_message=> params[:request][:request_message] )

    if !@request.save
      redirect_to root_path #ns change this to SHOW ERROR MESSAGE instead
    #else show success page
    end

  end


  def show

  end

  def delete
    p = Request.where(:pet_id=>params[:pet_id]).first
    p.delete 
    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  
  def respond
  end


  def show
    #@user = User.find(1)
	if current_user
		@curr_user = User.find(current_user.id)
		@user = User.find(current_user.id)
	else
		redirect_to new_user_session_path, notice: 'You are not logged in.'
	end


    #@users = User.find(params[:curr_user])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PetHugs (Home)</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-frontpage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PetHugs</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Your Profile', curr_user_path() %>
                    </li>
                    <li>
                        <%= link_to 'Find a pet!', search_pets_path() %>
                    </li>
                    <li>
                        <% if user_signed_in? %>
  							<%= link_to('Logout', destroy_user_session_path, :class => "btn btn-link", :method => :delete) %>        
						<% else %>
  							<%= link_to('Login', new_user_session_path, :class => "btn btn-link")  %>  
						<% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">Welcome to PetHugs!</h1>
                </div>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr>

        <div class="row">
            <div class="col-sm-8">
                <h2>What We Do</h2>
                <p>School getting you down? Crowd too big at Sproul's PetHugs? Need a hug from a cute fluffy friend TODAY?</p>
                <p>Sign up and request your favorite local pet today! Show up at your scheduled time and enjoy hours of fun and therapeutic pet time!!</p>
                <p>
                    <% if user_signed_in? %>
  							<%= link_to 'Find a pet!', search_pets_path(), :class => "btn btn-default btn-lg" %>   
						<% else %>
  							<%= link_to('Sign up!', new_user_session_path, :class => "btn btn-default btn-lg")  %>  
						<% end %>
                </p>
            </div>
            <div class="col-sm-4">
                <h2>Contact Us</h2>
                <address>
                    <strong>PetHugs</strong>
                    <br>306 Soda Hall
                    <br>Berkeley, CA 94709
                    <br>
                </address>
                <address>
                    <abbr title="Phone">P:</abbr>(123) 456-7890
                    <br>
                    <abbr title="Email">E:</abbr> <a href="mailto:#">pethugs@berkeley.edu</a>
                </address>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="https://cl.ly/0r3O1e2e1b3f/Screen%20Shot%202016-11-28%20at%201.46.43%20PM.png" alt="">
                <h2>Cap</h2>
                <p><i>"Soft siberian husky puppy! He was so lazy and cute!"</i> – Takara</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="https://cl.ly/3l0W3A3t3C3d/Screen%20Shot%202016-11-28%20at%201.50.01%20PM.png" alt="">
                <h2>Keroppi</h2>
                <p><i>"Was very affectionate and was super energetic when playing with toys! Pethugs was like a really chill and personal cat cafe!"</i> – Jiwoo</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="https://cl.ly/3O0B0d0t3m0t/Screen%20Shot%202016-11-28%20at%201.46.53%20PM.png" alt="">
                <h2>Rocky</h2>
                <p><i>"I LOVE SAMOYEDS!"</i> – Jake</p>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; PetHugs 2016</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj2New</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>


</body>
</html>

app/views/pets/_pet.html.erb
	<th> 
		<%= pet.name %> 
	</th>
	<th>
		<%= pet.animal_type %>
	</th> 
	<th>
		<%= pet.characteristic %>
	</th>

	<th>
		<%= button_to "REQUEST THIS PET", new_request_path(pet_id: pet.id, user_id: @user_id), :class => "button medium", :method => :patch %> 
	</th>

app/views/pets/new.html.erb
Add a Pet for others to Play with!
<%= simple_form_for @pet, url: {action: "create"} do |f| %>
  <%= f.input :name %>
  <%= f.input :characteristic %>
  <b>* Pet type</b> <%= f.select :animal_type, ['Dog', 'Cat', 'Hamster', 'Rabbit', 'Gerbil', 'Raccoon', 'Llamas', 'Other']%>
  <%= f.input :image_url %>
  <div><b>* Date</b> <%= f.date_field :start_date %></div>
  <div><b>* Time</b> <%= f.time_field :start_time %></div>
  <%= f.label :duration, "* Duration(hrs)" %>
  <%= f.select :duration, [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5], :include_blank => true%>
  <%= f.input :address %>
<%= hidden_field_tag(:curr_user, @user_id) %>
  <%= f.button :submit %>
<% end %>

app/views/pets/pet.html.erb
<% if pet.user_id.to_i != @user_id.to_i %>
	<th> 
		<%= pet.name %> 
	</th>
	<th>
		<%= pet.animal_type %>
	</th> 
	<th>
		<%= pet.characteristic %>
	</th>

	<th>
		<%= button_to "REQUEST THIS PET", new_request_path(pet_id: pet.id, user_id: @user_id), :class => "button medium", :method => :patch %> 
	</th>
<%end%>

app/views/pets/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PetHugs (Search)</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-modal.css" rel="stylesheet">
    <link href="css/bootstrap-modal-bs3patch.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/heroic-features.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">PetHugs</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Your Profile', curr_user_path() %>
                    </li>
                    <li>
                        <%= link_to 'Find a pet!', search_pets_path() %>
                    </li>
                    <li>
            <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :class => "btn btn-link", :method => :delete) %>        
            <% else %>
                <%= link_to('Login', new_user_session_path, :class => "btn btn-link")  %>  
            <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>Find a hug!</h1>
            <p>Find and request any type of pet from all over Berkeley.</p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                    <h4>

      <%= simple_form_for @pet, url: {action: "show"} do |f| %>
  <%= f.label :animal_type, "Type of Animal" %> 
  <%= f.select :animal_type, ['Cat', 'Dog', 'Hamster', 'Rabbit', 'Gerbil', 'Raccoon', 'Llamas', 'Other'], :include_blank => true%>   
  <%= f.label :start_date, "Starting Date" %>
  <%= f.date_field :start_date %> 
  <%= f.label :duration, "Duration" %> 
  <%= f.select :duration, [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5], :include_blank => true%>   
   <%= f.button :submit, "Filter" %>
 <% end %>


            </h4>
            <br>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">
          <% if @pets != nil %> 
            <%@pets.each do |p| %>
              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <%= image_tag p.image_url, height: '500', width: '800'%>
                      <div class="caption">
                          <h3><%=p.name%></h3>
                          <p> <%=p.animal_type%><br> </p>
                          <p> <b>Characteristic: </b><%=p.characteristic%><br> </p>
                          <p> <b>Location:</b> <%=p.address%></p>
                          <p> <b>Start date:</b> <%=p.start_date%></p>
                          <p> <b>Start time:</b> <%=p.start_time.strftime("%H:%M")%></p>
                          <p> <b>Availability:</b> <%=p.duration%> hours</p>
                              <%= button_to "Request this pet!", new_request_path(pet_id: p.id, user_id: @user_id), :class => "btn btn-primary", :method => :patch %> 
                          </p>
                      </div>
                  </div>
              </div>
            <% end %>
          <% end %>

        </div>
        <!-- /.row -->

        <hr>


        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; PetHugs 2016</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/bootstrap-modal.js"></script>
    <script src="js/bootstrap-modalmanager.js"></script>

</body>

</html>

app/views/request/create.html.erb
<h1>Your request has been made!</h1>

Once the owner approves of your request, you can play with <%=@pet.name %> at <%= @pet.address%>.

<br></br>
He will be there for <%=@pet.duration%> hours starting [START DATE]!
<br></br>
You can check the status of your request for this pet by viewing your profile.
<br></br>

<h3>YAY PETS <3 </h3>

  <%= button_to('Delete Request', delete_request_path(pet_id: @pet.id, user_id: current_user.id), :method => :post) %>

<br></br>

		<%= button_to("Return to Home Page", root_path, :class => "button medium", :method => :get) %> 
<br></br>

		  <%= button_to('My Profile', curr_user_path(user_id: current_user.id), :method => :get) %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PetHugs (Profile)</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/heroic-features.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">PetHugs</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Your Profile', curr_user_path() %>
                    </li>
                    <li>
                        <%= link_to 'Find a pet!', search_pets_path() %>
                    </li>
                    <li>
                        <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :class => "btn btn-link", :method => :delete) %>        
            <% else %>
                <%= link_to('Login', new_user_session_path, :class => "btn btn-link")  %>  
            <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>Welcome back, <%=@curr_user.email%></h1>
            <p>Check below for the status on requests you've made, and check if anyone has requested to play with your pets.</p>
            <p>
            <%= link_to "Add a pet", new_pet_path(:curr_user=>@user.id), { :class=>"btn btn-primary btn-large" } %>

            </p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>My Requests</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

          <%@user.requests.each do |request| %>
              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <%= image_tag request.pet.image_url, height: '500', width: '800'%>
                      <div class="caption">
                          <h3><%=request.pet.name%></h3>
                          <p> <b>Location:</b> <%=request.pet.address%></p>
                          <p> <b>Start Date: </b> <%=request.pet.start_date%></p>
                          <p> <b>Start Time: </b><%=request.pet.start_time.strftime("%H:%M")%> </p>
                          <p>    <b>Availability:</b> <%=request.pet.duration%> hours</p>
                          <p><b>Approval Status:</b>    <% if request.status==1%>
                                    Approved!
                                  <%elsif request.status == -1%>
                                    Pending...
                                  <%else%>
                                    Declined
                                  <%end%>
                          </p>

                              <%= button_to('Cancel Request?', delete_request_path(pet_id: request.pet.id, user_id: current_user.id), :class=>"btn btn-primary btn-large", :method => :post) %>
                          </p>
                      </div>
                  </div>
              </div>
            <% end %>

        </div>
        <!-- /.row -->

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>My Pets</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <%@user.pets.each do |p| %>
              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <%= image_tag p.image_url, height: '500', width: '800'%>
                      <div class="caption">
                          <h3><%=p.name%></h3>
                          <p> <!-- <%=p.animal_type%><br> --> </p>
                          <p> <b>Location:</b> <%=p.address%></p>
                          <p> <b>Start date:</b> <%=p.start_date%></p>
                          <p> <b>Start time:</b> <%=p.start_time.strftime("%H:%M")%> </p>
                          <p> <b>Availability:</b> <%=p.duration%> hours</p>
                          <p> <%= button_to "Delete Pet", delete_pet_path(pet_id: p.id, user_id: @user.id), :class => "btn btn-danger", :method => :post %> </p>
                          <p>    
                            <% if p.requests != nil%> 
                              <%p.requests.each do |request|%>
                                <b>Request from:</b> <%=request.user.email%>
                                <b>Request Message: </b> <%=request.request_message%>
                                 
                                <%= button_to "Accept", accept_request_path(request_id: request.id), :class => "btn btn-primary btn-large", :method => :post %> <%= button_to "Decline", decline_request_path(request_id: request.id), :class => "btn btn-default", :method => :post %> 
                               <% end %>
                              <%end%>
                          </p>
                          </p>
                      </div>
                  </div>
              </div>
             <% end %>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; PetHugs 2016</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/users/user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>